services:
  mysqldb:
    container_name: employee-db-container
    image: mysql:8.3.0
    environment:
      MYSQL_USER: appuser
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3316:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      employee-app-mysql-network:

  springboot-employee-rest-api:
    container_name: employee-api-container
    build:
      context: ./employee-test
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on: 
      - mysqldb
    environment:
      - spring.jpa.hibernate.ddl-auto=update
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/test
      - spring.datasource.username=appuser
      - spring.datasource.password=password
    networks:
      employee-app-mysql-network:
    restart: on-failure

networks:
  employee-app-mysql-network:





